server:
  port: 9999
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.211.50.12:3306/filesearch_test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: g13917274919jj
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  data:
    redis:
      port: 6379
      password: g13917274919jj
      database: 15
      host: 129.211.50.12
  elasticsearch:
    uris: http://129.211.50.12:9200
    host: 129.211.50.12
    port: 9200
    protocol: http
    username: elastic
    password: g13917274919jj

minio:
  endpoint: http://129.211.50.12:9000 # minio api 地址
  fileHost: http://129.211.50.12:9000 # minio 对象存储访问地址
  accessKey: o0VppD3jmcrkuWVAlLxf
  secretKey: BtCOHXcYZTXwFzjO1AksF5rGnyqkmjV6whvxjnlC
  bucketName: multi-type-source-file


mybatis:
  # mapper映射文件
  mapper-locations: classpath:mapper/*.xml
  # 数据库字段实体类文件
  type-aliases-package: com.gzh.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

